on:
  create
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          
      - name: Criar aviso de branch nova
        run: echo "Branch nova"
